version: "3.8"
services:

  # springapi:
  #   image: aleslash/springapi
  #   container_name: springapi
  #   ports:
  #     - "8080:8080"
  #     - "9000:9000"
  #   networks:
  #     - metricas
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
    
  # nodecaller:
  #   image: aleslash/nodecaller
  #   container_name: nodecaller
  #   networks:
  #     - metricas
  #   depends_on: ["springapi"]
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    networks:
      - metricas
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    deploy:
      restart_policy:
        condition: on-failure
  
  grafana:
    image: grafana/grafana:7.1.1
    container_name: grafana
    ports:
      - 3000:3000
    networks: 
      - metricas
    volumes:
      - grafana_data:/var/lib/grafana


networks:
  metricas:
    driver: "bridge"

volumes: 
  grafana_data: